version: '3.4'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    container_name: web
    environment:
      FLASK_ENV: development
      FLASK_APP: app/main
    ports:
      - "${PORT}:80"
    volumes:
      - "${PWD}:/app"
    command: flask run --host=0.0.0.0 --port 80
